### ISSUE TITLE
Cleancode: avoid to hardcode env variables and se typing module for forcing constants.

### ISSUE THREAD

**Issue by giorgiozoppi** [nuvolaris/nuvolaris-operator#16]
In modern Python rhe pattern for assuring that constants are constant o have some hint about that it is the following:
````python
from typing import Final
MAX_ITERATION: Final = 1
for x in range(MAX_ITERATION):
    print(x)
MAX_ITERATION = 101
````
This happens from Python 3.8 and allows type checkers to control if there's a need of  constant. In this case 
you enable mypy to check if you or someone is changing the constant. Also we have is a good pratice isolate constant 
in a constant.py module and import. In this way the constant doesn't pollute the namespace.  Like in C++, here the idea is you just pay what you get, what you don't get you don't care.

**Comment by msciabarra** [comment]
at some point we will enforce typing - at the moment we do not
